import { KJUR } from "jsrsasign";
export function generateSignature(sdkKey, sdkSecret, meetingNumber, role) {
  const iat = Math.round(new Date().getTime() / 1000) - 30;
  const exp = iat + 60 * 60 * 2;
  const oHeader = { alg: "HS256", typ: "JWT" };

  const oPayload = {
    sdkKey: sdkKey,
    appKey: sdkKey,
    mn: meetingNumber,
    role: role,
    iat: iat,
    exp: exp,
    tokenExp: exp,
  };

  const sHeader = JSON.stringify(oHeader);
  const sPayload = JSON.stringify(oPayload);
  const sdkJWT = KJUR.jws.JWS.sign("HS256", sHeader, sPayload, sdkSecret);
  return sdkJWT;
}

export const language = {
  "de-DE": {
    join: "Beitreten",
    name: "Name",
    language: "Sprache",
    password: "Passwort",
    meeting_id: "Meeting-ID",
    set_username_message: "Definieren Sie den Benutzernamen!",
    set_meeting_id_message: "Definieren Sie die Besprechungs-ID!",
    set_password_message: "Definieren Sie ein Passwort!",
    role: "Rolle",
    host: "Host",
    participant: "Teilnehmer",
  },
  "es-ES": {
    join: "Unirse",
    name: "Nombre",
    language: "Idioma",
    password: "Contraseña",
    meeting_id: "ID de Reunión",
    set_username_message: "¡Defina el nombre de usuario!",
    set_meeting_id_message: "¡Defina el ID de la Reunión!",
    set_password_message: "¡Defina una contraseña!",
    role: "Rol",
    host: "Anfitrión",
    participant: "Participante",
  },
  "en-US": {
    join: "Join",
    name: "Name",
    language: "Language",
    password: "Password",
    meeting_id: "Meeting ID",
    set_username_message: "Set username!",
    set_meeting_id_message: "Set meeting ID!",
    set_password_message: "Set password!",
    role: "Role",
    host: "Host",
    participant: "Participant",
  },
  "fr-FR": {
    join: "Rejoindre",
    name: "Nom",
    language: "Langue",
    password: "Mot de passe",
    meeting_id: "Identifiant de Réunion",
    set_username_message: "Définir le nom d'utilisateur!",
    set_meeting_id_message: "Définir l'ID de la Réunion!",
    set_password_message: "Définir un mot de passe!",
    role: "Rôle",
    host: "Hôte",
    participant: "Participant",
  },
  "jp-JP": {
    join: "参加する",
    name: "名前",
    language: "言語",
    password: "パスワード",
    meeting_id: "会議 ID",
    set_username_message: "ユーザー名を設定してください！",
    set_meeting_id_message: "会議 ID を設定してください！",
    set_password_message: "パスワードを設定してください！",
    role: "役割",
    host: "ホスト",
    participant: "参加者",
  },
  "pt-PT": {
    join: "Juntar-se",
    name: "Nome",
    language: "Idioma",
    password: "Senha",
    meeting_id: "ID da Reunião",
    set_username_message: "Defina o nome de usuário!",
    set_meeting_id_message: "Defina o ID da Reunião!",
    set_password_message: "Defina uma senha!",
    role: "Função",
    host: "Anfitrião",
    participant: "Participante",
  },
  "ru-RU": {
    join: "Присоединиться",
    name: "Имя",
    language: "Язык",
    password: "Пароль",
    meeting_id: "ID собрания",
    set_username_message: "Укажите имя пользователя!",
    set_meeting_id_message: "Укажите идентификатор собрания!",
    set_password_message: "Укажите пароль!",
    role: "Роль",
    host: "Хост",
    participant: "Участник",
  },
  "zh-CN": {
    join: "加入",
    name: "名称",
    language: "语言",
    password: "密码",
    meeting_id: "会议ID",
    set_username_message: "设置用户名！",
    set_meeting_id_message: "设置会议 ID!",
    set_password_message: "设置密码！",
    role: "角色",
    host: "主持人",
    participant: "参与者",
  },
  "zh-TW": {
    join: "加入",
    name: "名稱",
    language: "語言",
    password: "密碼",
    meeting_id: "會議 ID",
    set_username_message: "設置用戶名！",
    set_meeting_id_message: "設置會議 ID!",
    set_password_message: "設置密碼！",
    role: "角色",
    host: "主持人",
    participant: "參與者",
  },
  "ko-KO": {
    join: "가입하다",
    name: "이름",
    language: "언어",
    password: "비밀번호",
    meeting_id: "회의 ID",
    set_username_message: "사용자 이름 설정!",
    set_meeting_id_message: "회의 ID 설정!",
    set_password_message: "비밀번호 설정!",
    role: "역할",
    host: "호스트",
    participant: "참가자",
  },
  "vi-VN": {
    join: "Tham gia",
    name: "Tên",
    language: "Ngôn ngữ",
    password: "Mật khẩu",
    meeting_id: "ID Cuộc họp",
    set_username_message: "Đặt tên người dùng!",
    set_meeting_id_message: "Đặt ID cuộc họp!",
    set_password_message: "Đặt mật khẩu!",
    role: "Vai trò",
    host: "Chủ nhà",
    participant: "Người tham dự",
  },
  "it-IT": {
    join: "Unirsi",
    name: "Nome",
    language: "Lingua",
    password: "Password",
    meeting_id: "ID Riunione",
    set_username_message: "Imposta il nome utente!",
    set_meeting_id_message: "Imposta l'ID della Riunione!",
    set_password_message: "Imposta una password!",
    role: "Ruolo",
    host: "Host",
    participant: "Partecipante",
  },
  "id-ID": {
    join: "Bergabung",
    name: "Nama",
    language: "Bahasa",
    password: "Kata sandi",
    meeting_id: "ID Rapat",
    set_username_message: "Tetapkan nama pengguna!",
    set_meeting_id_message: "Tetapkan ID rapat!",
    set_password_message: "Tetapkan kata sandi!",
    role: "Peran",
    host: "Pemimpin",
    participant: "Peserta",
  },
  "nl-NL": {
    join: "Lid worden",
    name: "Naam",
    language: "Taal",
    password: "Wachtwoord",
    meeting_id: "Vergaderings-ID",
    set_username_message: "Stel gebruikersnaam in!",
    set_meeting_id_message: "Stel vergader-ID in!",
    set_password_message: "Stel een wachtwoord in!",
    role: "Rol",
    host: "Host",
    participant: "Deelnemer",
  },
};
